name = "memos-worker"
compatibility_date = "2025-08-19"
main = "src/index.js"
[assets]
directory = "./src/public"
run_worker_first = [
	"/api/*"
]

[[d1_databases]]
binding = "DB"
database_id = "a9ead2e4-5d28-4488-b0ad-32397edd13e7"
database_name = "notes-db"

[[kv_namespaces]]
binding = "NOTES_KV"
id = "887a07d6e820422abf518bb2575b7535"
preview_id = ""

[[r2_buckets]]
binding = "NOTES_R2_BUCKET"
bucket_name = "notes-r2-bucket"
preview_bucket_name = "notes-files-preview"
